name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: apt update -y && apt install -y python3 python3-pipa
      - run: pip install uv
      - run: uv sync
      - run: uv run pytest
